### ISSUE TITLE
KeyError: 'rf' on workspace with catkin_make artifacts

### ISSUE THREAD

**Issue by mintar** [catkin/catkin_tools#150]
I get the following error:

    $ catkin build
    [build] Runtime: 0.0 seconds 
    Traceback (most recent call last):
      File "/usr/local/bin/catkin", line 9, in <module>
        load_entry_point('catkin-tools==0.2.1', 'console_scripts', 'catkin')()
      File "/usr/local/lib/python2.7/dist-packages/catkin_tools-0.2.1-py2.7.egg/catkin_tools/commands/catkin.py", line 198, in main
        sys.exit(args.main(args) or 0)
      File "/usr/local/lib/python2.7/dist-packages/catkin_tools-0.2.1-py2.7.egg/catkin_tools/verbs/catkin_build/cli.py", line 270, in main
        summarize_build=opts.summarize  # Can be True, False, or None
      File "/usr/local/lib/python2.7/dist-packages/catkin_tools-0.2.1-py2.7.egg/catkin_tools/verbs/catkin_build/build.py", line 488, in build_isolated_workspace
        "or clean the build space.".format(context.build_space_abs)))
    KeyError: 'rf'

The workspace was previously built with `catkin_make` and contains the old build and devel folders:

    $ ls -a 
    .  ..  build  .catkin_tools  .catkin_workspace  devel  src

After `rm -rf build devel`, it works. Tested both on the current .deb version (0.2.1-1) and latest `master` branch (0afc6f9c). I'm using ROS Hydro on Ubuntu 12.04.

**Comment by jbohren** [comment]
So, `rf` on that line is coming from the CLI colorizer (red foreground).

@wjwwood Do you know why the colorizer would break like this?

**Comment by tlind** [comment]
+1, same issue here

**Comment by jbohren** [comment]
This should be fixed in #153
