### ISSUE TITLE
Source catkin_tools broken?

### ISSUE THREAD

**Issue by davetcoleman** [catkin/catkin_tools#187]
catkin build gives me the error:

```
==> Expanding alias 'bd' from 'catkin bd' to 'catkin build --cmake-args -DCMAKE_BUILD_TYPE=Debug'
Creating build space directory, '/home/dave/ros/ws_amazon/build' 
----------------------------------------------------------------------------------------------------------------------------------------
Profile:                     default
Extending:             [env] /home/dave/ros/ws_moveit_other/devel:/home/dave/ros/ws_moveit/devel:/home/dave/ros/ws_base/devel:/opt/ros/indigo
Workspace:                   /home/dave/ros/ws_amazon
Source Space:       [exists] /home/dave/ros/ws_amazon/src
Build Space:        [exists] /home/dave/ros/ws_amazon/build
Devel Space:       [missing] /home/dave/ros/ws_amazon/devel
Install Space:     [missing] /home/dave/ros/ws_amazon/install
DESTDIR:                     None
----------------------------------------------------------------------------------------------------------------------------------------
Isolate Develspaces:         False
Install Packages:            False
Isolate Installs:            False
----------------------------------------------------------------------------------------------------------------------------------------
Additional CMake Args:       -DCMAKE_BUILD_TYPE=Debug
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
----------------------------------------------------------------------------------------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
----------------------------------------------------------------------------------------------------------------------------------------
Workspace configuration appears valid.
---------------------------------------------------------------------------------------------------------------------------------------- 
[build] Runtime: 0.0 seconds 
Traceback (most recent call last):
  File "/usr/local/bin/catkin", line 9, in <module>
    load_entry_point('catkin-tools==0.2.2', 'console_scripts', 'catkin')()
  File "/usr/local/lib/python2.7/dist-packages/catkin_tools-0.2.2-py2.7.egg/catkin_tools/commands/catkin.py", line 219, in main
    sys.exit(args.main(args) or 0)
  File "/usr/local/lib/python2.7/dist-packages/catkin_tools-0.2.2-py2.7.egg/catkin_tools/verbs/catkin_build/cli.py", line 295, in main
    summarize_build=opts.summarize  # Can be True, False, or None
  File "/usr/local/lib/python2.7/dist-packages/catkin_tools-0.2.2-py2.7.egg/catkin_tools/verbs/catkin_build/build.py", line 592, in build_isolated_workspace
    packages_to_be_built, packages_to_be_built_deps, all_packages = determine_packages_to_be_built(packages, context)
  File "/usr/local/lib/python2.7/dist-packages/catkin_tools-0.2.2-py2.7.egg/catkin_tools/verbs/catkin_build/build.py", line 163, in determine_packages_to_be_built
    workspace_packages = find_packages(context.source_space_abs, exclude_subspaces=True, warnings=[])
TypeError: find_packages() got an unexpected keyword argument 'warnings'
```

I remove the ``warnings=[]`` from two locations in build.py and it works again.

I double checked by downloading a fresh copy of master, and it is indeed broken.

**Comment by dirk-thomas** [comment]
You need to install the latest version of `catkin_pkg` (0.2.8).

@jbohren I guess the package dependencies should state the minimum version which #163 does not seem to address.

**Comment by wjwwood** [comment]
Yeah, you need to update `catkin_pkg`, I have a follow up commit that fixes that locally. I just pushed it: ffcded2

**Comment by wjwwood** [comment]
@davetcoleman thanks for the report.

**Comment by davetcoleman** [comment]
the apt-get version of ``catkin_pkg`` is only 0.2.7

**Comment by davetcoleman** [comment]
im still without a build system, not sure how to fix. ive never installed from source catkin_pkg and don't really want to

**Comment by davetcoleman** [comment]
ok, i installed catkin_tools from apt-get and was able to continue my work just now

**Comment by wjwwood** [comment]
@dirk-thomas any idea why the `catkin_pkg` deb isn't public yet? Did you sync the mirrors or ask @tfoote to do it?

@davetcoleman I'm not sure why the deb isn't the right version yet, but your choices are to update `catkin_pkg` manually or use the released version of `catkin_tools`, until the newer version of `catkin_pkg` is available.
