### ISSUE TITLE
catkin init: ImportError: No module named osrf_pycommon.process_utils

### ISSUE THREAD

**Issue by mariiiiiia** [catkin/catkin_tools#312]
I install catkin tools in Ubuntu 14.04 LTS and when I try to initialize my first workspace I get this error:

```
vassilis@vassilis:~/example_catkin_ws$ catkin init 
Traceback (most recent call last):
  File "/usr/local/bin/catkin", line 9, in <module>
    load_entry_point('catkin-tools==0.3.1', 'console_scripts', 'catkin')()
  File "/usr/local/lib/python2.7/dist-packages/catkin_tools/commands/catkin.py", line 265, in main
    catkin_main(sysargs)
  File "/usr/local/lib/python2.7/dist-packages/catkin_tools/commands/catkin.py", line 165, in catkin_main
    argument_preprocessors = create_subparsers(parser, verbs)
  File "/usr/local/lib/python2.7/dist-packages/catkin_tools/commands/catkin.py", line 58, in create_subparsers
    desc = load_verb_description(verb)
  File "/usr/local/lib/python2.7/dist-packages/catkin_tools/commands/catkin.py", line 45, in load_verb_description
    return entry_point.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/catkin_tools/verbs/catkin_build/__init__.py", line 17, in <module>
    from .cli import main
  File "/usr/local/lib/python2.7/dist-packages/catkin_tools/verbs/catkin_build/cli.py", line 48, in <module>
    from catkin_tools.context import Context
  File "/usr/local/lib/python2.7/dist-packages/catkin_tools/context.py", line 32, in <module>
    from .resultspace import get_resultspace_environment
  File "/usr/local/lib/python2.7/dist-packages/catkin_tools/resultspace.py", line 30, in <module>
    from osrf_pycommon.process_utils import execute_process
ImportError: No module named osrf_pycommon.process_utils

```

P.S.: I've tried both "install from source" and "with apt-get install python-catkin-tools" and get the same error. Using Python 2.7.6

**Comment by wjwwood** [comment]
Hi @mariiiiiia, based on your traceback, I believe you have a newer version of `catkin_tools` which uses `osrf_pycommon` which you installed with `pip` or from calling `python setup.py install`, since parts of the traceback are from `/usr/local/lib/...`. These directories always override the `/usr/lib/...` directory which `apt-get` installs into. So you need to make sure to remove `catkin_tools` from `/usr/local/lib`, otherwise the it will not use the one you've installed from `apt-get`.

Since this is a known conflict between `apt-get` and `pip`, I'm going to close this for now. Feel free to continue to comment and ask questions, and I can reopen it if necessary.
