### ISSUE TITLE
catkin build with linux groups

### ISSUE THREAD

**Issue by cpaxton** [catkin/catkin_tools#316]
We are trying to share a catkin workspace on a server, but it looks like catkin_build keeps setting permissions so we cannot do this. Example:

[build] Runtime: 0.1 seconds 
Traceback (most recent call last):
  File "/usr/bin/catkin", line 9, in <module>
    load_entry_point('catkin-tools==0.3.0', 'console_scripts', 'catkin')()
  File "/usr/lib/python2.7/dist-packages/catkin_tools/commands/catkin.py", line 219, in main
    sys.exit(args.main(args) or 0)
  File "/usr/lib/python2.7/dist-packages/catkin_tools/verbs/catkin_build/cli.py", line 296, in main
    summarize_build=opts.summarize  # Can be True, False, or None
  File "/usr/lib/python2.7/dist-packages/catkin_tools/verbs/catkin_build/build.py", line 678, in build_isolated_workspace
    running_jobs = queue_ready_packages(ready_packages, running_jobs, job_queue, context, force_cmake)
  File "/usr/lib/python2.7/dist-packages/catkin_tools/verbs/catkin_build/build.py", line 139, in queue_ready_packages
    job = CMakeJob(package, path, context, force_cmake)
  File "/usr/lib/python2.7/dist-packages/catkin_tools/verbs/catkin_build/job.py", line 142, in __init__
    self.commands = self.get_commands()
  File "/usr/lib/python2.7/dist-packages/catkin_tools/verbs/catkin_build/job.py", line 185, in get_commands
    env_cmd = create_env_file(self.package, self.context)
  File "/usr/lib/python2.7/dist-packages/catkin_tools/verbs/catkin_build/job.py", line 130, in create_env_file
    generate_env_file(sources, env_file_path)
  File "/usr/lib/python2.7/dist-packages/catkin_tools/verbs/catkin_build/common.py", line 93, in generate_env_file
    os.chmod(env_file_path, stat.S_IXUSR | stat.S_IWUSR | stat.S_IRUSR)
OSError: [Errno 1] Operation not permitted: '/home/costar/catkin_ws/build/ObjRecRANSAC/build_env.sh'

cpaxton3@thin6:/home/costar/catkin_ws$ ls -al build/ObjRecRANSAC/
total 528
drwxrwx---  4 cli53 lcsr-costar   4096 Apr 11 15:22 .
drwxrwx--- 22 cli53 lcsr-costar   4096 Apr 11 15:18 ..
-rwxrwx---  1 cli53 lcsr-costar   1218 Apr 11 15:22 build_env.sh
-rw-rwx---  1 cli53 lcsr-costar  50391 Apr 11 15:18 CMakeCache.txt
drwxrwx--- 10 cli53 lcsr-costar   4096 Apr 11 15:20 CMakeFiles
-rw-rwx---  1 cli53 lcsr-costar   4201 Apr 11 15:18 cmake_install.cmake
-rw-rwx---  1 cli53 lcsr-costar 442884 Apr 11 15:18 libGreedy.a
-rw-rwx---  1 cli53 lcsr-costar  16205 Apr 11 15:18 Makefile
drwxrwx---  6 cli53 lcsr-costar     97 Apr 11 15:18 src

This error is very easy to reproduce: just create a directory shared by catkin and try to access with multiple users.

**Comment by wjwwood** [comment]
@cpaxton thanks for reporting the issue. I think the line `os.chmod(env_file_path, stat.S_IXUSR | stat.S_IWUSR | stat.S_IRUSR)` is the culprit, but I'm not sure how it should be changed. Can you suggest an alternative set of permissions. It will be necessary for catkin to create, destroy, and change permissions on files inside the build folder. I don't think that is avoidable.

**Comment by cpaxton** [comment]
Maybe it would be best to give group read/write/execute permission to files created by catkin?

**Comment by cpaxton** [comment]
Perhaps a better option is to make catkin_tools honor umask when modifying file permissions.

**Comment by jbohren** [comment]
Note that this is a problem with `build_env.sh`, which doesn't exist in the current master.

```
OSError: [Errno 1] Operation not permitted: '/home/costar/catkin_ws/build/ObjRecRANSAC/build_env.sh'
```
