### ISSUE TITLE
catkin clean --all crashes

### ISSUE THREAD

**Issue by wjwwood** [catkin/catkin_tools#320]
I think `catkin clean -a` and `catkin clean --all` no longer make sense (they're the default behavior now), but when I run them I get:

```
william@farl /tmp/quickstart_ws
% catkin clean -a
usage: catkin [-h] [-a] [--test-colors] [--version]
              [--force-color | --no-color | --locate-extra-shell-verbs]
              [build | clean | config | create | env | init | list | locate | profile]
              ...
catkin: error: unrecognized arguments: -a

william@farl /tmp/quickstart_ws
% catkin clean --all
Traceback (most recent call last):
  File "/usr/local/bin/catkin", line 9, in <module>
    load_entry_point('catkin-tools==0.3.1', 'console_scripts', 'catkin')()
  File "/usr/local/lib/python2.7/site-packages/catkin_tools/commands/catkin.py", line 265, in main
    catkin_main(sysargs)
  File "/usr/local/lib/python2.7/site-packages/catkin_tools/commands/catkin.py", line 260, in catkin_main
    sys.exit(args.main(args) or 0)
  File "/usr/local/lib/python2.7/site-packages/catkin_tools/verbs/catkin_clean/cli.py", line 340, in main
    profiles = get_profile_names(workspace_path)
NameError: global name 'get_profile_names' is not defined
```

The second crashes in an unexpected way to me.

I tried these because the documentation in https://github.com/catkin/catkin_tools/pull/318 still references `--all` as an option to `catkin clean` (I'm in the process of fixing that).

**Comment by jbohren** [comment]
@wjwwood I fixed the doc errors, but for the second, are you sure you're on master? I don't see that call on line 340: https://github.com/catkin/catkin_tools/blob/master/catkin_tools/verbs/catkin_clean/cli.py#L340

**Comment by jbohren** [comment]
@wjwwood Are you still seeing this problem?

**Comment by wjwwood** [comment]
Let me check.

**Comment by wjwwood** [comment]
Nope.
