### ISSUE TITLE
DYLD_LIBRARY_PATH missing in 'make test'

### ISSUE THREAD

**Issue by mkoval** [catkin/catkin_tools#354]
### System Info

* Operating System: 15.2.0 Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; root:xnu-3248.20.55~2/RELEASE_X86_64 x86_64 i386 MacBookPro10,1 Darwin
* Python Version: Python 2.7.11
* Version of catkin_tools: 0.4 and 6bc4b53590e4f1f2f4ed757c4f813e13f2adc370
* ROS Distro: indigo

### Build / Run Issue

I am building a non-Catkin `CMake` package with `catkin build` that uses `make test` to run tests through CMake's CTest integration. I typically run the tests like this:
```console
$ catkin build -i -p 1 --no-deps --make-args test -- my_package
```
This previously worked fine on OS X. Running the tests now fails because the dynamic linker cannot find the libraries build by `my_package`:
```
      Start 43: test_VanDerCorput
43/43 Test #43: test_VanDerCorput ...........................***Exception: Other  0.01 sec
dyld: Library not loaded: @rpath/libdart.6.0.dylib
  Referenced from: /Users/mkoval/development/test-ws/build/aikido/tests/util/test_VanDerCorput
  Reason: image not found
```

I am able to manually run the test (i.e. by invoking the test executable) after sourcing `setup.bash`. This works because `setup.bash` adds the necessary directory to `DYLD_LIBRARY_PATH`:
```
$ echo $DYLD_LIBRARY_PATH
/Users/mkoval/development/test-ws/devel/lib:/opt/ros/indigo/lib
```
I suspect something in `catkin build` is stripping `DYLD_LIBRARY_PATH` from the environment before running `make test`.

This is similar to #350, since that is an issue with `LD_LIBRARY_PATH` being cleared, but I am not sure if it is exactly the same: I am not having any problems with `catkin_tools_prebuild`. I also tried the proposed fix #353 to no avail.

**Comment by jbohren** [comment]
> This is similar to #350, since that is an issue with `LD_LIBRARY_PATH` being cleared, but I am not sure if it is exactly the same: I am not having any problems with `catkin_tools_prebuild`. I also tried the proposed fix #353 to no avail.

So in #350, a `LD_LIBRARY_PATH`  which was modified before running `catkin build` was getting cleared, and it wasn't actually anything wrong with `catkin_tools_prebuild`, but just the fakeroot libs that needed to be auto-loaded weren't being loaded.

I'm sorry this isn't working for you. In catkin_tools `0.3.1`, the environments used for build commands came from `build_env.sh` which would source the resulting workspace before running `make`. Now, the executor loads the environment from within Python. However, these two mechanisms should achieve the same exact result. The environment loading is computed here: https://github.com/catkin/catkin_tools/blob/master/catkin_tools/jobs/utils.py#L28-L78

Does your example work with `catkin_make_isolated`? If so, can you post a simple example that demonstrates the problem? Can you also post the output of `catkin config`?

**Comment by jbohren** [comment]
@mkoval Currently this test is passing in #355: https://github.com/catkin/catkin_tools/pull/355/commits/39303f4ec5592f3e605bc56361d052e42b601389

Can you modify that test in such a way that it fails?

You can run it locally like this:

```bash
nosetests -s tests.system.verbs.catkin_build.test_unit_tests
```

**Comment by mkoval** [comment]
That test actually fails for me!

```
_______________________________________________________________________________________
Errors << test_pkg:make /private/var/folders/kq/sgcjcqx95h38_1qgl4n4qqgw0000gn/T/N1oW9u/logs/test_pkg/build.make.001.log
Running tests...
/usr/local/Cellar/cmake/3.5.1/bin/ctest --force-new-ctest-process
Test project /private/var/folders/kq/sgcjcqx95h38_1qgl4n4qqgw0000gn/T/N1oW9u/build/test_pkg
    Start 1: vanilla_test
1/1 Test #1: vanilla_test .....................***Exception: Other  0.14 sec
dyld: Library not loaded: libvanilla.dylib
  Referenced from: /private/var/folders/kq/sgcjcqx95h38_1qgl4n4qqgw0000gn/T/N1oW9u/build/test_pkg/vanilla_test_app
  Reason: image not found


0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.14 sec

The following tests FAILED:
	  1 - vanilla_test (OTHER_FAULT)
Errors while running CTest
make: *** [test] Error 8
cd /private/var/folders/kq/sgcjcqx95h38_1qgl4n4qqgw0000gn/T/N1oW9u/build/test_pkg; catkin build --get-env test_pkg | catkin env -si  /usr/bin/make test --jobserver-fds=6,7 -j; cd -
.......................................................................................
Failed << test_pkg:make            [ Exited with code 2 ]
Failed <<< test_pkg                [ 0.2 seconds ]
[build] Summary: 0 of 1 packages succeeded.
[build] Ignored: 3 packages were skipped or are blacklisted.
[build] Warnings: None.
[build] Abandoned: No packages were abandoned.
[build] Failed: 1 packages failed.
[build] Runtime: 0.5 seconds total.

F
======================================================================
FAIL: Test ctest-based tests
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/mkoval/catkin_tools/tests/utils.py", line 137, in decorated
    return f(*args, **kwds)
  File "/Users/mkoval/catkin_tools/tests/system/verbs/catkin_build/test_unit_tests.py", line 63, in test_ctest
    'test_pkg', '--make-args', 'test'])
AssertionError

----------------------------------------------------------------------
Ran 3 tests in 18.850s

FAILED (failures=1)
```

**Comment by jbohren** [comment]
> That test actually fails for me!

Well that was easy.

I added another test to #355 which does the same, but with a `merged` develspace. Can you try running that too? It's the same command as before.

I'd like to know why it's failing on your machine, but not on the CI. One thing I noticed was:

> ```
> ...
> /usr/local/Cellar/cmake/3.5.1/bin/ctest
> ...
> ```

It's possible that this is a problem being introduced by CMake 3.5.1, or because you're on OS X > 9.5. (which is what Travis CI uses).

**Comment by jbohren** [comment]
@wjwwood Could we run the new tests on that 10.10 machine at OSRF?

**Comment by wjwwood** [comment]
I think you still have access to that machine. If not I can set it up again. I just ran the tests on my mac (10.11) and it fails:

```
test 1
    Start 1: vanilla_test

1: Test command: /private/var/folders/qb/38qj2qz532z5456q623r9nhc0000gn/T/2PmhxZ/build/test_pkg/vanilla_test_app
1: Test timeout computed to be: 9.99988e+06
1: dyld: Library not loaded: libvanilla.dylib
1:   Referenced from: /private/var/folders/qb/38qj2qz532z5456q623r9nhc0000gn/T/2PmhxZ/build/test_pkg/vanilla_test_app
1:   Reason: image not found
1/1 Test #1: vanilla_test .....................***Exception: Other  0.16 sec
```

**Comment by jbohren** [comment]
> I think you still have access to that machine. If not I can set it up again. I just ran the tests on my mac (10.11) and it fails:

With which version of CMake?

**Comment by jbohren** [comment]
@wjwwood Also is this related to SIP?

**Comment by wjwwood** [comment]
@jbohren could be SIP, but that shouldn't affect `catkin_tools` versus `catkin_make_isolated` or version 0.3.1 and 0.4.x.

**Comment by jbohren** [comment]
> @jbohren could be SIP, but that shouldn't affect catkin_tools versus catkin_make_isolated or version 0.3.1 and 0.4.x.

Well, `0.3.1` was using `build_env.sh` for this, whereas now we're using a subprocess call.

**Comment by jbohren** [comment]
Yeah this looks like a SIP issue, it's failing on El Cap only:
https://travis-ci.org/catkin/catkin_tools/builds/125132043 

Note that the failures on python3 otherwise are due to this bug:
https://github.com/rfk/pyenchant/issues/45

**Comment by jbohren** [comment]
Disabled spellcheck on OS X, so now we can see this failing only on El Cap:
https://travis-ci.org/catkin/catkin_tools/builds/125139824

**Comment by jbohren** [comment]
Since this is also failing on 0.3.1, I'm removing the regression label.

**Comment by wjwwood** [comment]
I'm not sure what to do about this one. @jbohren's pr adds tests that fail, but I think the best thing to address those particular failures is to disable SIP or for the user to manually pass `-DCMAKE_MACOSX_RPATH=ON` when build on their mac's (might not work in all cases).
