### ISSUE TITLE
Unexplicit error when cmake is not installed

### ISSUE THREAD

**Issue by medrimonia** [catkin/catkin_tools#437]
I just reinstalled a computer and tried to build one of my project based on catkin (without using ROS) and I faced an unexplicit error (at least for neophytes like me)

```
Traceback (most recent call last):
  File "/usr/local/bin/catkin", line 11, in <module>
    load_entry_point('catkin-tools==0.4.4', 'console_scripts', 'catkin')()
  File "/usr/local/lib/python2.7/dist-packages/catkin_tools/commands/catkin.py", line 267, in main
    catkin_main(sysargs)
  File "/usr/local/lib/python2.7/dist-packages/catkin_tools/commands/catkin.py", line 262, in catkin_main
    sys.exit(args.main(args) or 0)
  File "/usr/local/lib/python2.7/dist-packages/catkin_tools/verbs/catkin_build/cli.py", line 420, in main
    summarize_build=opts.summarize  # Can be True, False, or None
  File "/usr/local/lib/python2.7/dist-packages/catkin_tools/verbs/catkin_build/build.py", line 441, in build_isolated_workspace
    prebuild=True)
  File "/usr/local/lib/python2.7/dist-packages/catkin_tools/jobs/catkin.py", line 447, in create_catkin_build_job
    occupy_job=True
  File "/usr/local/lib/python2.7/dist-packages/catkin_tools/execution/stages.py", line 91, in __init__
    raise ValueError('Command stage must be a list of strings: {}'.format(cmd))
ValueError: Command stage must be a list of strings: [None, '/home/medrimonia/rhoban/workspace/src/catkin', '--no-warn-unused-cli', '-DCATKIN_DEVEL_PREFIX=/home/medrimonia/rhoban/workspace/devel_release/.private/catkin', '-DCMAKE_INSTALL_PREFIX=/home/medrimonia/rhoban/workspace/install_release', '-DCMAKE_BUILD_TYPE=Release']
```
I have been able to track down the source of the error which was the value of `CMAKE_EXEC` which was `None`. Although I agree that it is obvious that cmake has to be installed, I think that error could be more explicit if a specific error was thrown by checking the value of `CMAKE_EXEC` at line 439 of `catkin.py`.

**Comment by wjwwood** [comment]
Yeah, there used to be a better message, but maybe it regressed or was lost in refactoring. I'd appreciate a pr for this if anyone has time.
