### ISSUE TITLE
Issue with catkin build 

### ISSUE THREAD

**Issue by FaboNo** [catkin/catkin_tools#534]
### System Info

* Operating System: Ubuntu 16.04
* Python Version: 2.7.12
* Version of catkin_tools: catkin-tools 0.4.4
* ROS Distro: kinetic

### Build / Run Issue

Never happen before but If I create a directory `mkdir -p catkin_ws/src` and then enter `catkin build` I have the following error:
```

    emeric@emeric-desktop:~/catkin_plan_ws$ catkin build
    ------------------------------------------------------
    Profile:                     default
    Extending:             [env] /opt/ros/kinetic
    Workspace:                   /home/emeric
    ------------------------------------------------------
    Source Space:       [exists] /home/emeric/src
    Log Space:         [missing] /home/emeric/logs
    Build Space:        [exists] /home/emeric/build
    Devel Space:        [exists] /home/emeric/devel
    Install Space:      [unused] /home/emeric/install
    DESTDIR:            [unused] None
    ------------------------------------------------------
    Devel Space Layout:          linked
    Install Space Layout:        None
    ------------------------------------------------------
    Additional CMake Args:       DCMAKE_BUILT_TYPE=Release
    Additional Make Args:        None
    Additional catkin Make Args: None
    Internal Make Job Server:    True
    Cache Job Environments:      False
    ------------------------------------------------------
    Whitelisted Packages:        None
    Blacklisted Packages:        None
    ------------------------------------------------------
    Workspace configuration appears valid.
    
    NOTE: Forcing CMake to run for each package.
    ------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/bin/catkin", line 9, in <module>
        load_entry_point('catkin-tools==0.4.4', 'console_scripts', 'catkin')()
      File "/usr/lib/python2.7/dist-packages/catkin_tools/commands/catkin.py", line 267, in main
        catkin_main(sysargs)
      File "/usr/lib/python2.7/dist-packages/catkin_tools/commands/catkin.py", line 262, in catkin_main
        sys.exit(args.main(args) or 0)
      File "/usr/lib/python2.7/dist-packages/catkin_tools/verbs/catkin_build/cli.py", line 420, in main
        summarize_build=opts.summarize  # Can be True, False, or None
      File "/usr/lib/python2.7/dist-packages/catkin_tools/verbs/catkin_build/build.py", line 283, in build_isolated_workspace
        workspace_packages = find_packages(context.source_space_abs, exclude_subspaces=True, warnings=[])
      File "/usr/lib/python2.7/dist-packages/catkin_pkg/packages.py", line 86, in find_packages
        packages = find_packages_allowing_duplicates(basepath, exclude_paths=exclude_paths, exclude_subspaces=exclude_subspaces, warnings=warnings)
      File "/usr/lib/python2.7/dist-packages/catkin_pkg/packages.py", line 146, in find_packages_allowing_duplicates
        xml, filename=filename, warnings=warnings)
      File "/usr/lib/python2.7/dist-packages/catkin_pkg/package.py", line 509, in parse_package_string
        raise InvalidPackage('The manifest must contain a single "package" root tag')
    catkin_pkg.package.InvalidPackage: The manifest must contain a single "package" root tag

Besides the build and devel folders are created in my home directory not in the catkin one. 

```
Besides I noticed that the build and devel folders have been created on the home directory and not in the catkin directory.

I guess I messed up something but I do not what and thus how to fix it.

Thank you for your help

**Comment by FaboNo** [comment]
I found out that I had a .catkin_tools on my home directory :( I deleted it and now it is working as usual
Issue is closed

**Comment by gavanderhoorn** [comment]
Seems to be a cross-post of [Catkin issue - error when I am initializing a ws](https://answers.ros.org/question/314991) on ROS Answers.
