### ISSUE TITLE
catkin config --extend /opt/ros/kinetic Resultspace does not exist.

### ISSUE THREAD

**Issue by realtime-neil** [catkin/catkin_tools#579]
```
$ catkin config --install --workspace /home/user/copy_catkin_ws --extend /opt/ros/kinetic
Traceback (most recent call last):
  File "/usr/bin/catkin", line 11, in <module>
    load_entry_point('catkin-tools==0.4.5', 'console_scripts', 'catkin')()
  File "/usr/lib/python2.7/dist-packages/catkin_tools/commands/catkin.py", line 272, in main
    catkin_main(sysargs)
  File "/usr/lib/python2.7/dist-packages/catkin_tools/commands/catkin.py", line 267, in catkin_main
    sys.exit(args.main(args) or 0)
  File "/usr/lib/python2.7/dist-packages/catkin_tools/verbs/catkin_config/cli.py", line 138, in main
    remove=opts.remove_args)
  File "/usr/lib/python2.7/dist-packages/catkin_tools/context.py", line 212, in load
    ctx = Context(**context_args)
  File "/usr/lib/python2.7/dist-packages/catkin_tools/context.py", line 301, in __init__
    self.extend_path = extend_path if extend_path else None
  File "/usr/lib/python2.7/dist-packages/catkin_tools/context.py", line 584, in extend_path
    raise ValueError("Resultspace path '{0}' does not exist.".format(value))
ValueError: Resultspace path '/opt/ros/kinetic' does not exist.
```

This started happening _today_ on code that hasn't been touched otherwise. What happened in the last two days?

**Comment by timonegk** [comment]
The error means that there is no folder `/opt/ros/kinetic`, this is not a problem with `catkin_tools`.
