### ISSUE TITLE
build: ctrl+c does not always work

### ISSUE THREAD

**Issue by NikolausDemmel** [catkin/catkin_tools#59]
I often get stuck in a terminal where the Python process is stuck (not killable with `ctrl-c`) if I interupt it with `ctrl-c` at an "unconvenient" time. In this case I hit `ctrl+c` just after `Found '251' packages in 0.3 seconds.` is displayed (but no package has started building). I get the following backtrace but am only left with the option to kill the python process manually.

```
$ catkin i -DCMAKE_BUILD_TYPE=Release
==> Expanding alias 'i' from 'catkin i -DCMAKE_BUILD_TYPE=Release' to 'catkin install -DCMAKE_BUILD_TYPE=Release'
==> Expanding alias 'install' from 'catkin install -DCMAKE_BUILD_TYPE=Release' to 'catkin build --install -DCMAKE_BUILD_TYPE=Release'
-----------------------------------------------------------------
Workspace:                   /Users/demmeln/work/hydro_ws
Buildspace:                  /Users/demmeln/work/hydro_ws/build
Develspace:                  /Users/demmeln/work/hydro_ws/devel
Installspace:                /Users/demmeln/work/hydro_ws/install
DESTDIR:                     None
-----------------------------------------------------------------
Isolate Develspaces:         False
Install Packages:            True
Isolate Installs:            False
-----------------------------------------------------------------
Additional CMake Args:       -DCMAKE_BUILD_TYPE=Release
Additional Make Args:        None
Additional catkin Make Args: None
-----------------------------------------------------------------
Found '251' packages in 0.3 seconds.
^C[build] Runtime: 2.8 seconds
Traceback (most recent call last):
  File "/usr/local/bin/catkin", line 9, in <module>
    load_entry_point('catkin-tools==0.0.0', 'console_scripts', 'catkin')()
  File "/Users/demmeln/work/catkin_tools/catkin_tools/commands/catkin.py", line 192, in main
    sys.exit(args.main(args) or 0)
  File "/Users/demmeln/work/catkin_tools/catkin_tools/verbs/catkin_build/cli.py", line 183, in main
    lock_install=not opts.no_install_lock
  File "/Users/demmeln/work/catkin_tools/catkin_tools/verbs/catkin_build/build.py", line 411, in build_isolated_workspace
    ready_packages = get_ready_packages(packages_to_be_built, running_jobs, completed_packages)
  File "/Users/demmeln/work/catkin_tools/catkin_tools/verbs/catkin_build/build.py", line 92, in get_ready_packages
    depends = get_cached_recursive_build_depends_in_workspace(package, workspace_packages)
  File "/Users/demmeln/work/catkin_tools/catkin_tools/verbs/catkin_build/common.py", line 341, in get_cached_recursive_build_depends_in_workspace
    cache[package.name] = get_recursive_build_depends_in_workspace(package, workspace_packages)
  File "/Users/demmeln/work/catkin_tools/catkin_tools/verbs/catkin_build/common.py", line 374, in get_recursive_build_depends_in_workspace
    dep_depends = dep_pkg.build_depends + dep_pkg.buildtool_depends + dep_pkg.run_depends
  File "/usr/local/lib/python2.7/site-packages/catkin_pkg/package.py", line 112, in __getattr__
    [run_depends.append(deepcopy(d)) for d in self.exec_depends + self.build_export_depends if d not in run_depends]
  File "/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 237, in _deepcopy_tuple
    y.append(deepcopy(a, memo))
  File "/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 154, in deepcopy
    d = id(x)
KeyboardInterrupt
```

**Comment by jbohren** [comment]
The execution pipeline has been completely re-implemented in #249. If this continues to occur, please re-open it.
