### ISSUE TITLE
No longer able to extend workspace: KeyError: '_Context__extend_path'

### ISSUE THREAD

**Issue by Levi-Armstrong** [catkin/catkin_tools#754]
Just started running into an issue trying to extend a workspace.
```
Traceback (most recent call last):
  File "/usr/local/bin/catkin", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/catkin_tools/commands/catkin.py", line 265, in main
    catkin_main(sysargs)
  File "/usr/local/lib/python3.8/dist-packages/catkin_tools/commands/catkin.py", line 260, in catkin_main
    sys.exit(args.main(args) or 0)
  File "/usr/local/lib/python3.8/dist-packages/catkin_tools/verbs/catkin_config/cli.py", line 177, in main
    context = Context.load(
  File "/usr/local/lib/python3.8/dist-packages/catkin_tools/context.py", line 256, in load
    ctx.load_env()
  File "/usr/local/lib/python3.8/dist-packages/catkin_tools/context.py", line 493, in load_env
    self.warnings += [clr(
KeyError: '_Context__extend_path'
```

**Comment by Levi-Armstrong** [comment]
Had the actual error messaged printed it would have identified the issue which I found after navigating context.py line 493 where I just had to clean the workspace then extend and everything worked.
